### ISSUE TITLE
Question. Writing difference to third file in JSON format.

### ISSUE THREAD

**Issue by shed909** [ZoomerAnalytics/jsondiff#13]
I've got two JSON files pulled from the same website, which I'm importing a day apart using json.dump with "indent=4" to format it.

I would like to compare the old JSON file with the new JSON file with the possibility that the newer file will have additional objects.
If there are additional objects, I'd like to export them to a third JSON file with the same format.

**Comment by fzumstein** [comment]
You're free to create whatever structured json out of the diff that jsondiff gives you but there's nothing built in for what you want.
