### ISSUE TITLE
List ordering is preserved

### ISSUE THREAD

**Issue by steph-ben** [ZoomerAnalytics/jsondiff#8]
I'm trying to compare and diff some json structures.
I expect the following to be equal, but it's not:
```
>>> jsondiff.diff(
    [u'all_users', u'viewer'],
    [u'viewer', u'all_users']
)
{delete: [0], insert: [(1, u'all_users')]}
```

Shall we consider ordering when comparing ?

**Comment by ericremoreynolds** [comment]
Hi Stephane,

This behaviour is standard, indeed if you use `==` to compare those two lists in Python it will say they are different:

    >>> [u'all_users', u'viewer'] == [u'viewer', u'all_users']
    False

The unordered equivalent of a list is a set - jsondiff supports these, though they do not exist in standard JSON.

**Comment by steph-ben** [comment]
This is just making sens ... thanks for this clarification
